import { site } from "@/lib/site";
import type { LandingUi } from "../types";

export default {
  home: "Startseite",
  breadcrumb: "Navigationspfad",
  product: "Produkt",
  platforms: "KI-Plattformen",
  solutions: "Lösungen",
  integrations: "Integrationen",
  company: "Unternehmen",
  legal: "Rechtliches",
  primaryCta: `Für ${site.priceMonthlyUsd}\u00a0$/Monat starten`,
  secondaryCta: "Kostenlos selbst hosten",
  learnMore: "Mehr erfahren",
  faqEyebrow: "FAQ",
  faqTitle: "Häufige Fragen",
  relatedFeatures: "Passende Funktionen",
  otherPlatforms: "Weitere KI-Plattformen tracken",
  otherPlatformsMuted: "mit denselben Prompts.",
  relatedSolutions: "Weitere Lösungen",
  moreIntegrations: "Weitere Integrationen dieser Kategorie",
  allIntegrations: "Alle Integrationen",
  viewAll: "Alle ansehen",
  status: { beta: "Beta", "coming-soon": "Demnächst" },
  integrationCount: "{n} Integrationen",
  byTeam: "Nach Team",
  byIndustry: "Nach Branche",
  menu: {
    aiVisibility: "AI Visibility",
    seo: "SEO-Suite",
    analytics: "Analytics & Attribution",
    optimize: "Optimieren & berichten",
    developers: "Entwickler",
  },
  factsLabel: "Produktfakten",
  trackedIn: "Tracken Sie Ihre Marke in",
  howItWorks: "So funktioniert es",
  step: "Schritt",
  engineBy: "von",
  answerFrom: "Antwort von",
  mentioned: "Erwähnt",
  cited: "Zitiert",
  sources: "Quellen",
  stickyTitle: "Open-Source AI Visibility & SEO",
  relatedTitle: "Zusammen noch stärker.",
  relatedMuted: "Eine Plattform, ein Datensatz.",
  solutionsTitle: "Für jedes Team,",
  solutionsMuted: "das die KI-Suche betrifft.",
  integrationsTitle: "Verbinden Sie die Tools, die Sie schon nutzen",
  integrationTitle: "{name}-Integration",
  securityNav: "Sicherheit",
  supportNav: "Support",
  allSolutions: "Alle Lösungen",
  resources: "Ressourcen",
  pages: {
    enterprise: "Enterprise",
    customers: "Kunden",
    caseStudies: "Playbooks",
    press: "Pressekit",
    careers: "Karriere",
    webinars: "Webinare",
    exhibitions: "Veranstaltungen",
    partnerProgram: "Partnerprogramm",
    affiliateProgram: "Empfehlungsprogramm",
    affiliateTerms: "Bedingungen des Empfehlungsprogramms",
    aiAgentInstructions: "Anweisungen für KI-Agenten",
    entityConnections: "Entity-Verknüpfungen",
    aiVisibilityCheck: "Kostenloser KI-Sichtbarkeits-Check",
    blog: "Blog",
  },
  homepage: {
    sphere: {
      eyebrow: "Für jedes Team",
      title: "Die KI-Suche betrifft alles.",
      muted: "Nicht nur das Marketing.",
      body: "Wie Kunden Produkte vergleichen, wie Bewerber Sie als Arbeitgeber sehen, was Menschen über Ihren Service hören – KI-Antworten prägen all das. AutoSEO zeigt aus jedem Blickwinkel, was die KI sagt, damit jedes Team handeln kann.",
      center: "Was die KI über Sie sagt",
      centerSub: "prägt Kauf, Vertrauen und Reputation",
    },
    sphereLabels: ["SEO & GEO", "Content", "PR & Marke", "Kundenerlebnis", "Agenturen", "E-Commerce"],
    stats: [
      { value: 16, label: "KI-Engines", note: "ChatGPT, Perplexity, Gemini, Claude, AI Overviews und mehr" },
      { value: 143, label: "Märkte", note: "Land und Sprache pro Prompt" },
      { value: 100, suffix: "+", label: "MCP-Tools", note: "Für Claude Code, Codex, Cursor und ChatGPT" },
      { value: 29, label: "Site-Audit-Checks", note: "Plus Lighthouse für Mobil und Desktop" },
    ],
    platform: {
      eyebrow: "Alles an einem Ort",
      title: "Die AutoSEO-Plattform",
      muted: "im Überblick.",
      body: "Alle Werkzeuge, um die Sichtbarkeit Ihrer Marke in der KI-Suche zu messen und auszubauen – direkt neben einer kompletten SEO-Suite.",
    },
  },
  promptsHint: "Tracken Sie sie in AutoSEO und sehen Sie, welche Marken die KI empfiehlt.",
  solutionsHub: {
    meta: {
      title: "AI-Visibility-Lösungen für Teams & Branchen",
      description:
        "Wie GEO-, SEO-, Content-, PR- und Agentur-Teams sowie Branchen von E-Commerce bis Finanzen mit AutoSEO ihre Sichtbarkeit in der KI-Suche messen und verbessern.",
    },
    hero: {
      eyebrow: "Lösungen",
      title: "Die KI-Suche verändert die Arbeit jedes Teams.",
      muted: "So nutzt jedes Team AutoSEO.",
      subtitle:
        "Vom SEO-Team bis zur PR, von Agenturen bis zu regulierten Branchen: Sehen Sie, welche Prompts zählen, was KI-Engines sagen und wie Sie es verbessern – mit der Open-Source-Plattform für AI Visibility und SEO.",
    },
    teams: { eyebrow: "Nach Team", title: "Lösungen für Ihr Team" },
    industries: { eyebrow: "Nach Branche", title: "Lösungen für Ihre Branche" },
  },
} satisfies LandingUi;
