import type { Locale } from "../types";

/** UI strings of the company components (playbook pages, press assets). Content lives in `src/content/company`. */
export const companyLabels = {
  en: {
    caseStudies: { label: "Case studies", href: "/case-studies" },
    playbookEyebrow: "Playbook · methodology",
    disclaimerTitle: "Methodology, not a customer result",
    disclaimer:
      "This playbook describes how to run and measure the work in AutoSEO. It contains no customer data and promises no outcome: AI answers vary, and your results depend on your market, your content and the engines you track.",
    goal: "Goal",
    audience: "Who it's for",
    prompts: "Prompt set",
    promptsSubtitle: "Import it in AutoSEO under AI Visibility → Tracker → Import CSV (paste the text or upload the file).",
    placeholders: "Replace these placeholders before you import — the importer takes every line literally:",
    promptCount: "{n} prompts",
    download: "Download CSV",
    engines: "Engines to track",
    baseline: "Baseline measurement in AutoSEO",
    actions: "Actions",
    measure: "How to measure change",
    variance: "Expected variance",
    limitations: "Limitations",
    faq: "Questions about this playbook",
    reading: "Further reading",
    related: "More playbooks",
    ctaTitle: "Run this playbook in AutoSEO",
    ctaBody: "Every feature is included in the free self-hosted edition and in AutoSEO Cloud.",
    ctaPrimary: { label: "Start with AutoSEO Cloud", href: "/signup" },
    ctaSecondary: { label: "Self-host for free", href: "/self-hosting" },
    heroPrimary: { label: "Get the prompt set", href: "#prompts" },
    heroSecondary: { label: "All playbooks", href: "/case-studies" },
    logoDownload: "Download",
    screenshotOpen: "Open full size",
  },
  de: {
    caseStudies: { label: "Case Studies", href: "/de/case-studies" },
    playbookEyebrow: "Playbook · Methodik",
    disclaimerTitle: "Methodik, kein Kundenergebnis",
    disclaimer:
      "Dieses Playbook beschreibt, wie Sie die Arbeit in AutoSEO umsetzen und messen. Es enthält keine Kundendaten und verspricht kein Ergebnis: KI-Antworten schwanken, und Ihr Ergebnis hängt von Ihrem Markt, Ihren Inhalten und den getrackten Engines ab.",
    goal: "Ziel",
    audience: "Für wen",
    prompts: "Prompt-Set",
    promptsSubtitle: "Importieren Sie es in AutoSEO unter AI Visibility → Tracker → Import CSV (Text einfügen oder Datei hochladen).",
    placeholders:
      "Ersetzen Sie diese Platzhalter vor dem Import und passen Sie Artikel und Endungen an – der Import übernimmt jede Zeile wörtlich:",
    promptCount: "{n} Prompts",
    download: "CSV herunterladen",
    engines: "Zu trackende Engines",
    baseline: "Ausgangsmessung in AutoSEO",
    actions: "Maßnahmen",
    measure: "Veränderung messen",
    variance: "Erwartbare Schwankung",
    limitations: "Grenzen",
    faq: "Fragen zu diesem Playbook",
    reading: "Weiterlesen",
    related: "Weitere Playbooks",
    ctaTitle: "Dieses Playbook in AutoSEO umsetzen",
    ctaBody: "Alle Funktionen sind in der kostenlosen Self-Hosting-Version und in AutoSEO Cloud enthalten.",
    ctaPrimary: { label: "Mit AutoSEO Cloud starten", href: "/signup" },
    ctaSecondary: { label: "Kostenlos selbst hosten", href: "/self-hosting" },
    heroPrimary: { label: "Zum Prompt-Set", href: "#prompts" },
    heroSecondary: { label: "Alle Playbooks", href: "/de/case-studies" },
    logoDownload: "Herunterladen",
    screenshotOpen: "In voller Größe öffnen",
  },
} satisfies Record<Locale, Record<string, unknown>>;
