import { site } from "@/lib/site";
import type { LandingUi } from "../types";

export default {
  home: "Home",
  breadcrumb: "Breadcrumb",
  product: "Product",
  platforms: "AI platforms",
  solutions: "Solutions",
  integrations: "Integrations",
  company: "Company",
  legal: "Legal",
  primaryCta: `Start for $${site.priceMonthlyUsd}/month`,
  secondaryCta: "Self-host for free",
  learnMore: "Learn more",
  faqEyebrow: "FAQ",
  faqTitle: "Frequently asked questions",
  relatedFeatures: "Related features",
  otherPlatforms: "Track more AI platforms",
  otherPlatformsMuted: "with the same prompts.",
  relatedSolutions: "More solutions",
  moreIntegrations: "More integrations in this category",
  allIntegrations: "All integrations",
  viewAll: "View all",
  status: { beta: "Beta", "coming-soon": "Coming soon" },
  integrationCount: "{n} integrations",
  byTeam: "By team",
  byIndustry: "By industry",
  menu: {
    aiVisibility: "AI visibility",
    seo: "SEO suite",
    analytics: "Analytics & attribution",
    optimize: "Optimize & report",
    developers: "Developers",
  },
  factsLabel: "Product facts",
  trackedIn: "Track your brand in",
  howItWorks: "How it works",
  step: "Step",
  engineBy: "by",
  answerFrom: "Answer from",
  mentioned: "Mentioned",
  cited: "Cited",
  sources: "Sources",
  stickyTitle: "Open-source AI visibility & SEO",
  relatedTitle: "Works better together.",
  relatedMuted: "One platform, one dataset.",
  solutionsTitle: "Built for every team",
  solutionsMuted: "that AI search affects.",
  integrationsTitle: "Connect the tools you already use",
  integrationTitle: "{name} integration",
  securityNav: "Security",
  supportNav: "Support",
  allSolutions: "All solutions",
  resources: "Resources",
  pages: {
    enterprise: "Enterprise",
    customers: "Customers",
    caseStudies: "Playbooks",
    press: "Press kit",
    careers: "Careers",
    webinars: "Webinars",
    exhibitions: "Events",
    partnerProgram: "Partner program",
    affiliateProgram: "Referral program",
    affiliateTerms: "Referral program terms",
    aiAgentInstructions: "AI agent instructions",
    entityConnections: "Entity connections",
    aiVisibilityCheck: "Free AI visibility check",
    blog: "Blog",
  },
  homepage: {
    sphere: {
      eyebrow: "For every team",
      title: "AI search touches everything.",
      muted: "Not just marketing.",
      body: "How customers compare products, how candidates see you as an employer, what people hear about your service — AI answers shape all of it. AutoSEO shows what AI says from every angle, so every team can act on it.",
      center: "What AI says about you",
      centerSub: "shapes purchases, trust and reputation",
    },
    sphereLabels: ["SEO & GEO", "Content", "PR & brand", "Customer experience", "Agencies", "E-commerce"],
    stats: [
      { value: 16, label: "AI engines tracked", note: "ChatGPT, Perplexity, Gemini, Claude, AI Overviews and more" },
      { value: 143, label: "Markets", note: "Country and language per prompt" },
      { value: 100, suffix: "+", label: "MCP tools", note: "For Claude Code, Codex, Cursor and ChatGPT" },
      { value: 29, label: "Site audit checks", note: "Plus Lighthouse on mobile and desktop" },
    ],
    platform: {
      eyebrow: "Everything in one place",
      title: "The AutoSEO platform",
      muted: "at a glance.",
      body: "Every tool you need to measure and grow your brand's visibility in AI search — next to a complete SEO suite.",
    },
  },
  promptsHint: "Track them in AutoSEO to see which brands AI recommends.",
  solutionsHub: {
    meta: {
      title: "AI Visibility Solutions for Teams & Industries",
      description:
        "How GEO, SEO, content, PR, CX and agency teams — and industries from e-commerce to finance — use AutoSEO to track and improve their visibility in AI search.",
    },
    hero: {
      eyebrow: "Solutions",
      title: "AI search changes every team's work.",
      muted: "Here's how each one uses AutoSEO.",
      subtitle:
        "From the SEO team to PR, from agencies to regulated industries: see which prompts matter, what AI engines say and how to improve it — with the open-source AI visibility and SEO platform.",
    },
    teams: { eyebrow: "By team", title: "Solutions for your team" },
    industries: { eyebrow: "By industry", title: "Solutions for your industry" },
  },
} satisfies LandingUi;
