import "server-only";
import { S, type OpenApiOperation } from "../openapi-helpers";
import { adsQuery, catalogCoverageQuery, followupsQuery, productsQuery, retailersQuery, sentimentQuery } from "../insights-data";

const { str, strN, num, int, bool, arr, obj, ref } = S;
const period = ref("Period");
const pagination = ref("Pagination");
const date = { type: "string", format: "date" };
const cell = obj({ score: num, praise: int, neutral: int, criticism: int });
const aspectEnum = { type: "string", enum: ["quality", "price", "value", "performance", "features", "reliability", "design", "support", "service", "usability", "availability"] };

/** REST v1 operations: follow-up questions, sentiment scorecard, AI products / retailers / catalog coverage, AI ads (insights module). */
export const aiInsightsOperations: OpenApiOperation[] = [
  {
    method: "get",
    path: "/projects/{projectId}/fanouts/followups",
    operationId: "listFollowupQuestions",
    summary: "Follow-up questions",
    description: "Questions engines suggest next to answers: Perplexity related questions (followup), Google People Also Ask (paa) and related searches (related). Default: last 90 days.",
    tag: "Fan-outs",
    scope: "read",
    query: followupsQuery,
    data: arr(obj({ question: str, kind: { type: "string", enum: ["related", "paa", "followup"] }, frequency: int, models: arr(str), prompts: arr(obj({ id: str, text: str })), promptCount: int, firstSeen: date, lastSeen: date })),
    meta: { period, pagination },
  },
  {
    method: "get",
    path: "/projects/{projectId}/sentiment",
    operationId: "getSentiment",
    summary: "Sentiment & scorecard",
    description:
      "Sentiment overview (score 0–100, praise/neutral/criticism mix, top praised/criticised attributes, brand table) plus the aspect scorecard: score per fixed aspect = praise ÷ (praise + criticism) × 100 for the brand and tracked competitors, and a brand × model matrix.",
    tag: "Sentiment",
    scope: "read",
    query: sentimentQuery,
    data: obj({
      brand: str,
      you: obj({ score: num, scoreDelta: num, praise: num, neutral: num, criticism: num, statements: int }),
      compare: { type: ["object", "null"] },
      topPraise: arr(obj({ attribute: str, theme: strN, count: int, quote: str, answerId: str })),
      topCriticism: arr(obj({ attribute: str, theme: strN, count: int, quote: str, answerId: str })),
      brands: arr({ type: "object" }),
      daily: arr({ type: "object" }),
      scorecard: obj({
        scoreDefinition: str,
        you: obj({
          overall: num,
          overallDelta: num,
          classified: int,
          unclassified: int,
          strongest: { type: ["object", "null"] },
          weakest: { type: ["object", "null"] },
          biggestGap: { type: ["object", "null"] },
          aspects: arr(obj({ aspect: aspectEnum, score: num, delta: num, praise: int, neutral: int, criticism: int, leader: strN, leaderScore: num, rank: { type: ["integer", "null"] }, ranked: int })),
        }),
        brandsByAspect: arr(obj({ brand: str, isOwn: bool, aspects: { type: "object", additionalProperties: cell } })),
        brandsByModel: arr(obj({ brand: str, isOwn: bool, models: { type: "object", additionalProperties: cell } })),
      }),
    }),
    meta: { period },
  },
  {
    method: "get",
    path: "/projects/{projectId}/products",
    operationId: "listAiProducts",
    summary: "Products in AI answers",
    description: "Products AI engines name or show as shopping cards, with price, rating, stores, models and appearances (change vs previous period). `meta.brands` ranks brands by product appearances.",
    tag: "Shopping",
    scope: "read",
    query: productsQuery,
    data: arr(
      obj({
        productId: str,
        name: str,
        brand: strN,
        isOwn: bool,
        category: strN,
        sources: arr({ type: "string", enum: ["llm", "shopping"] }),
        price: num,
        oldPrice: num,
        currency: strN,
        rating: num,
        reviews: { type: ["integer", "null"] },
        models: arr(str),
        stores: arr(str),
        appearances: int,
        appearancesChange: num,
        lastSeen: date,
      }),
    ),
    meta: { period, pagination, totals: obj({ appearances: int, products: int, stores: int }), brands: arr({ type: "object" }) },
  },
  {
    method: "get",
    path: "/projects/{projectId}/products/retailers",
    operationId: "listAiRetailers",
    summary: "Retailers in AI shopping answers",
    tag: "Shopping",
    scope: "read",
    query: retailersQuery,
    data: arr(obj({ rank: int, retailer: str, domain: strN, appearances: int, appearancesChange: num, share: num, products: int, avgPrice: num, currency: strN })),
    meta: { period, pagination, totals: obj({ retailers: int, appearances: int }) },
  },
  {
    method: "get",
    path: "/projects/{projectId}/products/catalog",
    operationId: "getCatalogCoverage",
    summary: "Catalog coverage",
    description: "Your imported catalog vs the products AI names (matched by GTIN → URL → name): appearances per catalog product, never-recommended products and AI-cited vs catalog price.",
    tag: "Shopping",
    scope: "read",
    query: catalogCoverageQuery,
    data: arr(
      obj({
        catalogProductId: str,
        name: str,
        sku: strN,
        url: strN,
        category: strN,
        availability: strN,
        appearances: int,
        models: arr(str),
        lastSeen: { type: ["string", "null"], format: "date" },
        aiProductId: strN,
        aiName: strN,
        catalogPrice: num,
        currency: strN,
        aiPrice: num,
        aiCurrency: strN,
        aiStore: strN,
        priceDelta: num,
        priceDeltaPct: num,
      }),
    ),
    meta: {
      period,
      pagination,
      totals: obj({ catalog: int, matched: int, recommended: int, neverRecommended: int, priceMismatches: int, ownUnmatched: int }),
      ownProductsNotInCatalog: arr(obj({ id: str, name: str, appearances: int })),
    },
  },
  {
    method: "get",
    path: "/projects/{projectId}/ads",
    operationId: "listAiAds",
    summary: "Ads in AI answers",
    description: "Paid ads shown with AI answers: creatives, landing URLs with parsed click parameters, positions and appearances. `meta` adds advertiser share, daily series (% of prompts with ads, advertiser share per day) and organic vs paid presence per advertiser.",
    tag: "Ads",
    scope: "read",
    query: adsQuery,
    data: arr(
      obj({
        adId: str,
        advertiser: str,
        advertiserDomain: strN,
        isOwn: bool,
        headline: str,
        description: strN,
        landingUrl: strN,
        clickParams: { type: ["object", "null"], additionalProperties: str },
        campaign: obj({ source: strN, medium: strN, campaign: strN, term: strN, content: strN, network: strN }),
        avgPosition: num,
        rating: num,
        models: arr(str),
        appearances: int,
        appearancesChange: num,
        lastSeen: date,
      }),
    ),
    meta: {
      period,
      pagination,
      totals: obj({ appearances: int, ads: int, answersWithAds: int, answers: int, answersWithAdsPct: num, advertisers: int }),
      advertisers: arr({ type: "object" }),
      organicVsPaid: arr({ type: "object" }),
      daily: arr({ type: "object" }),
    },
  },
];
