import "server-only";
import { S, type OpenApiOperation } from "../openapi-helpers";
import { generateReportInput, listReportsQuery, reportDetailQuery, saveReportInput, saveTemplateInput, shareReportInput } from "../reports";
import { scheduleInputSchema, schedulePatchSchema } from "../report-schedules";

const { str, strN, int, bool, arr, obj } = S;

const urls = { url: str, shareUrl: strN };

const ops: OpenApiOperation[] = [
  {
    method: "get",
    path: "/projects/{projectId}/reports",
    operationId: "listReports",
    summary: "List reports",
    description: "HTML (agent / AI) reports and slide decks, newest first.",
    tag: "Reports",
    scope: "read",
    query: listReportsQuery,
    data: arr(obj({ id: str, kind: str, title: str, subtitle: strN, status: str, aiStatus: str, aiError: strN, slideCount: int, sizeBytes: int, shareEnabled: bool, createdBy: strN, createdAt: str, updatedAt: str, url: str })),
    meta: { total: int, remaining: int, limit: int, offset: int },
  },
  {
    method: "post",
    path: "/projects/{projectId}/reports",
    operationId: "saveReport",
    summary: "Save HTML report",
    description: "Stores a finished self-contained HTML report (open-seo `save_report`). 201 when created; pass reportId to replace one.",
    tag: "Reports",
    scope: "write",
    permission: "reports.manage",
    body: saveReportInput,
    status: 201,
    data: obj({ reportId: str, title: str, created: bool, htmlBytes: int, ...urls }),
  },
  {
    method: "post",
    path: "/projects/{projectId}/reports/generate",
    operationId: "generateReport",
    summary: "Generate AI report",
    description: "The app's AI writes an HTML report from live project data (job, 202) — poll GET /reports/{reportId} until aiStatus is ready.",
    tag: "Reports",
    scope: "write",
    permission: "reports.manage",
    body: generateReportInput,
    status: 202,
    data: obj({ reportId: str, status: str, jobId: strN, ...urls }),
  },
  {
    method: "get",
    path: "/projects/{projectId}/reports/{reportId}",
    operationId: "getReport",
    summary: "Get report",
    tag: "Reports",
    scope: "read",
    query: reportDetailQuery,
    data: obj({ id: str, kind: str, title: str, status: str, summary: strN, aiStatus: str, htmlBytes: int, share: { type: "object" }, html: { ...str, description: "Only with includeHtml=true (HTML reports)" }, ...urls }),
  },
  {
    method: "put",
    path: "/projects/{projectId}/reports/{reportId}",
    operationId: "replaceReport",
    summary: "Replace HTML report",
    tag: "Reports",
    scope: "write",
    permission: "reports.manage",
    body: saveReportInput.omit({ reportId: true }),
    data: obj({ reportId: str, title: str, created: bool, htmlBytes: int, ...urls }),
  },
  {
    method: "delete",
    path: "/projects/{projectId}/reports/{reportId}",
    operationId: "deleteReport",
    summary: "Delete report",
    description: "Permanently deletes the report; its share link stops working.",
    tag: "Reports",
    scope: "write",
    permission: "reports.manage",
    data: obj({ reportId: str, deleted: bool }),
  },
  {
    method: "post",
    path: "/projects/{projectId}/reports/{reportId}/share",
    operationId: "shareReport",
    summary: "Share link",
    description: "Enable / update (password, expiry) / disable the public link, or revoke it permanently (rotates the token).",
    tag: "Reports",
    scope: "write",
    permission: "reports.share",
    body: shareReportInput,
    data: obj({ reportId: str, shareEnabled: bool, hasPassword: bool, expiresAt: strN, ...urls }),
  },
  {
    method: "get",
    path: "/projects/{projectId}/report-templates",
    operationId: "listReportTemplates",
    summary: "List report templates",
    tag: "Reports",
    scope: "read",
    data: arr(obj({ id: str, kind: str, name: str, description: strN, instructions: strN, instructionsPreview: str, slideCount: int, updatedAt: str })),
  },
  {
    method: "post",
    path: "/projects/{projectId}/report-templates",
    operationId: "createReportTemplate",
    summary: "Create report template",
    tag: "Reports",
    scope: "write",
    permission: "reports.manage",
    body: saveTemplateInput.omit({ templateId: true }),
    status: 201,
    data: obj({ templateId: str, name: str, created: bool }),
  },
  {
    method: "put",
    path: "/projects/{projectId}/report-templates/{templateId}",
    operationId: "updateReportTemplate",
    summary: "Update report template",
    tag: "Reports",
    scope: "write",
    permission: "reports.manage",
    body: saveTemplateInput.omit({ templateId: true }),
    data: obj({ templateId: str, name: str, created: bool }),
  },
  {
    method: "delete",
    path: "/projects/{projectId}/report-templates/{templateId}",
    operationId: "deleteReportTemplate",
    summary: "Delete report template",
    tag: "Reports",
    scope: "write",
    permission: "reports.manage",
    data: obj({ templateId: str, deleted: bool }),
  },
];

const scheduleProps = {
  id: str,
  reportId: str,
  reportTitle: str,
  reportKind: str,
  cadence: { type: "string", enum: ["weekly", "monthly"] },
  weekday: int,
  monthDay: int,
  hour: int,
  timezone: str,
  recipients: arr(str),
  format: { type: "string", enum: ["link", "pptx", "both"] },
  formatLabel: str,
  rangePreset: str,
  rangeLabel: str,
  subject: strN,
  message: strN,
  linkExpiryDays: int,
  enabled: bool,
  description: str,
  nextRunAt: strN,
  lastSentAt: strN,
  lastStatus: { type: ["string", "null"], description: "sent | logged (SMTP not configured) | partial | failed" },
  lastError: strN,
  createdBy: strN,
  createdAt: str,
  updatedAt: str,
};
const schedule = obj(scheduleProps);

const delivery = obj({
  id: str,
  scheduleId: strN,
  reportId: str,
  trigger: { type: "string", enum: ["schedule", "manual"] },
  status: { type: "string", enum: ["sending", "sent", "logged", "partial", "failed"] },
  error: strN,
  format: str,
  recipients: arr(str),
  results: arr(obj({ email: str, delivered: bool, transport: str, error: strN })),
  periodLabel: strN,
  rangeFrom: strN,
  rangeTo: strN,
  shareUrl: { type: ["string", "null"], description: "Emailed read-only link (while valid)" },
  expiresAt: strN,
  pptxBytes: { type: ["integer", "null"] },
  views: int,
  createdAt: str,
  finishedAt: strN,
});

ops.push(
  {
    method: "get",
    path: "/projects/{projectId}/reports/{reportId}/schedules",
    operationId: "listReportSchedules",
    summary: "List delivery schedules",
    description: "Scheduled email deliveries of a report (weekly / monthly in a time zone) with next / last send; `meta.deliveries` has the 20 most recent sends. Needs reports.manage + reports.share.",
    tag: "Reports",
    scope: "read",
    permission: "reports.manage",
    data: arr(schedule),
    meta: { deliveries: arr(delivery) },
  },
  {
    method: "post",
    path: "/projects/{projectId}/reports/{reportId}/schedules",
    operationId: "createReportSchedule",
    summary: "Schedule report delivery",
    description:
      "Emails the report automatically: every send refreshes the data for the chosen period (resolved in the schedule's time zone), attaches the PowerPoint and/or an expiring read-only link, and fires the `report.sent` webhook. HTML (AI) reports support format `link` only.",
    tag: "Reports",
    scope: "write",
    permission: "reports.manage",
    body: scheduleInputSchema,
    status: 201,
    data: schedule,
  },
  {
    method: "get",
    path: "/projects/{projectId}/reports/{reportId}/schedules/{scheduleId}",
    operationId: "getReportSchedule",
    summary: "Get delivery schedule",
    tag: "Reports",
    scope: "read",
    permission: "reports.manage",
    data: obj({ ...scheduleProps, deliveries: arr(delivery) }),
  },
  {
    method: "patch",
    path: "/projects/{projectId}/reports/{reportId}/schedules/{scheduleId}",
    operationId: "updateReportSchedule",
    summary: "Update delivery schedule",
    description: "Partial update (timing, recipients, format, period, message, enabled = false pauses). PUT is accepted as an alias.",
    tag: "Reports",
    scope: "write",
    permission: "reports.manage",
    body: schedulePatchSchema,
    data: schedule,
  },
  {
    method: "delete",
    path: "/projects/{projectId}/reports/{reportId}/schedules/{scheduleId}",
    operationId: "deleteReportSchedule",
    summary: "Delete delivery schedule",
    description: "Stops future sends; links that were already emailed keep working until they expire.",
    tag: "Reports",
    scope: "write",
    permission: "reports.manage",
    data: obj({ scheduleId: str, deleted: bool }),
  },
  {
    method: "post",
    path: "/projects/{projectId}/reports/{reportId}/schedules/{scheduleId}/send",
    operationId: "sendReportScheduleNow",
    summary: "Send now",
    description: "Queues an immediate send of the schedule to its recipients (job, 202). The result appears in the schedule's deliveries.",
    tag: "Reports",
    scope: "write",
    permission: "reports.manage",
    status: 202,
    data: obj({ jobId: str, scheduleId: str, status: str }),
  },
);

/** REST v1 operations: reports, share links, templates and delivery schedules (reports module). */
export const reportsOperations = ops;
