import "server-only";
import { S, type OpenApiOperation } from "../openapi-helpers";
import { webhookDeliveriesQuery, webhookEndpointInput, webhookEndpointPatch, webhookTestBody } from "../webhooks";
import { WEBHOOK_EVENTS } from "@/server/webhooks/events";

const { str, strN, int, bool, arr, obj } = S;

const endpoint = obj({
  id: str,
  name: str,
  url: str,
  events: arr({ type: "string", enum: ["*", ...WEBHOOK_EVENTS] }),
  active: bool,
  secretPrefix: str,
  failureCount: { ...int, description: "Deliveries in a row that failed after all retries (≥ 5 over 24 h switch the endpoint off)." },
  disabledReason: strN,
  lastDeliveredAt: strN,
  lastFailureAt: strN,
  lastError: strN,
  createdAt: str,
  updatedAt: str,
});

const delivery = obj({
  id: str,
  endpointId: str,
  event: str,
  eventId: str,
  status: { type: "string", enum: ["pending", "retrying", "succeeded", "failed"] },
  attempt: int,
  responseCode: { type: ["integer", "null"] },
  responseBody: strN,
  error: strN,
  durationMs: { type: ["integer", "null"] },
  test: bool,
  replayOf: strN,
  deliveredAt: strN,
  createdAt: str,
  payload: { type: "object", description: "Signed JSON body: { id, event, createdAt, test, project, data }." },
});

const SIGNING =
  "Each POST carries `X-AutoSEO-Event`, `X-AutoSEO-Event-Id`, `X-AutoSEO-Delivery`, `X-AutoSEO-Timestamp` and `X-AutoSEO-Signature` = `sha256=` + hex HMAC-SHA256 of `{timestamp}.{raw body}` with the endpoint secret. Non-2xx responses are retried for ≈ 1.5 h with exponential backoff; HTTP 410 unsubscribes; endpoints failing for 24 h (5+ failed deliveries) are switched off.";

/** REST v1 operations: outbound webhook endpoints (event bus for Zapier / Make / n8n). */
export const webhooksOperations: OpenApiOperation[] = [
  {
    method: "get",
    path: "/projects/{projectId}/webhooks",
    operationId: "listWebhooks",
    summary: "List webhook endpoints",
    description: `Outbound webhooks of the project. Events: ${WEBHOOK_EVENTS.join(", ")}. ${SIGNING}`,
    tag: "Webhooks",
    scope: "read",
    permission: "settings.manage",
    data: arr(endpoint),
  },
  {
    method: "post",
    path: "/projects/{projectId}/webhooks",
    operationId: "createWebhook",
    summary: "Create webhook endpoint",
    description: "Subscribes a receiver URL (public http(s); private hosts only when allowlisted by an admin). The response contains `secret` — shown once.",
    tag: "Webhooks",
    scope: "write",
    permission: "settings.manage",
    body: webhookEndpointInput,
    status: 201,
    data: { ...endpoint, properties: { ...(endpoint.properties as object), secret: str } },
  },
  {
    method: "get",
    path: "/projects/{projectId}/webhooks/{webhookId}",
    operationId: "getWebhook",
    summary: "Get webhook endpoint",
    tag: "Webhooks",
    scope: "read",
    permission: "settings.manage",
    data: { ...endpoint, properties: { ...(endpoint.properties as object), recentDeliveries: arr(delivery) } },
  },
  {
    method: "put",
    path: "/projects/{projectId}/webhooks/{webhookId}",
    operationId: "updateWebhook",
    summary: "Update webhook endpoint",
    description: "Partial update. Re-enabling an endpoint resets its failure streak.",
    tag: "Webhooks",
    scope: "write",
    permission: "settings.manage",
    body: webhookEndpointPatch,
    data: endpoint,
  },
  {
    method: "delete",
    path: "/projects/{projectId}/webhooks/{webhookId}",
    operationId: "deleteWebhook",
    summary: "Delete webhook endpoint",
    tag: "Webhooks",
    scope: "write",
    permission: "settings.manage",
    data: obj({ id: str, deleted: bool }),
  },
  {
    method: "post",
    path: "/projects/{projectId}/webhooks/{webhookId}/rotate-secret",
    operationId: "rotateWebhookSecret",
    summary: "Rotate signing secret",
    tag: "Webhooks",
    scope: "write",
    permission: "settings.manage",
    data: obj({ id: str, secret: str }),
  },
  {
    method: "post",
    path: "/projects/{projectId}/webhooks/{webhookId}/test",
    operationId: "testWebhook",
    summary: "Send test event",
    description: "Sends a signed sample payload of the chosen event (`test: true`) right away and returns the delivery result.",
    tag: "Webhooks",
    scope: "write",
    permission: "settings.manage",
    body: webhookTestBody,
    data: delivery,
  },
  {
    method: "get",
    path: "/projects/{projectId}/webhooks/{webhookId}/deliveries",
    operationId: "listWebhookDeliveries",
    summary: "Delivery log",
    description: "Deliveries of the last 30 days, newest first, with payload, status, response code and error.",
    tag: "Webhooks",
    scope: "read",
    permission: "settings.manage",
    query: webhookDeliveriesQuery,
    data: arr(delivery),
  },
  {
    method: "post",
    path: "/projects/{projectId}/webhooks/{webhookId}/deliveries/{deliveryId}/replay",
    operationId: "replayWebhookDelivery",
    summary: "Replay delivery",
    description: "Queues the same payload again (same event id — receivers can dedupe; new signature).",
    tag: "Webhooks",
    scope: "write",
    permission: "settings.manage",
    status: 202,
    data: delivery,
  },
];
