import {
  Bell,
  BookOpen,
  Bot,
  Brain,
  Building2,
  Calendar,
  Car,
  ChartLine,
  CircleCheck,
  Code,
  Database,
  Download,
  Euro,
  Eye,
  FileText,
  Flag,
  Gauge,
  GitFork,
  Globe,
  Headset,
  Heart,
  Key,
  Landmark,
  Layers,
  Lightbulb,
  Link2,
  ListChecks,
  Lock,
  MapPin,
  Megaphone,
  MessageSquare,
  Newspaper,
  PenLine,
  Pill,
  Plane,
  Plug,
  Presentation,
  Radar,
  RefreshCw,
  Rocket,
  Search,
  Server,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Stethoscope,
  Store,
  Swords,
  Target,
  Terminal,
  TrendingUp,
  Users,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react";
import { cn } from "@/lib/utils";
import type { IconName } from "./types";

const icons: Record<IconName, LucideIcon> = {
  sparkles: Sparkles,
  radar: Radar,
  swords: Swords,
  heart: Heart,
  link: Link2,
  "git-fork": GitFork,
  "shopping-bag": ShoppingBag,
  megaphone: Megaphone,
  chart: ChartLine,
  euro: Euro,
  bot: Bot,
  "shield-check": ShieldCheck,
  "list-checks": ListChecks,
  "file-text": FileText,
  search: Search,
  "trending-up": TrendingUp,
  gauge: Gauge,
  presentation: Presentation,
  terminal: Terminal,
  plug: Plug,
  globe: Globe,
  "map-pin": MapPin,
  users: Users,
  building: Building2,
  lock: Lock,
  zap: Zap,
  layers: Layers,
  "message-square": MessageSquare,
  calendar: Calendar,
  target: Target,
  eye: Eye,
  workflow: Workflow,
  database: Database,
  key: Key,
  bell: Bell,
  book: BookOpen,
  lightbulb: Lightbulb,
  "check-circle": CircleCheck,
  refresh: RefreshCw,
  download: Download,
  code: Code,
  server: Server,
  brain: Brain,
  store: Store,
  stethoscope: Stethoscope,
  pill: Pill,
  car: Car,
  plane: Plane,
  landmark: Landmark,
  rocket: Rocket,
  newspaper: Newspaper,
  headset: Headset,
  pen: PenLine,
  flag: Flag,
};

/** Content icon in a soft brand tile. */
export function IconTile({ name, className }: { name: IconName; className?: string }) {
  const Icon = icons[name];
  return (
    <span
      className={cn(
        "grid size-10 shrink-0 place-items-center rounded-xl bg-brand-soft text-green-700 dark:text-green-300",
        className,
      )}
    >
      <Icon className="size-5" aria-hidden="true" />
    </span>
  );
}

export function ContentIcon({ name, className }: { name: IconName; className?: string }) {
  const Icon = icons[name];
  return <Icon className={className} aria-hidden="true" />;
}
